version: '3.4'

networks:
  loki:

services:
  fluent-bit:
    image: fluent/fluent-bit:1.6.6
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - LOG_PARSER=./parsers.conf
    deploy:
      mode: global
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    networks:
      - loki
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.7.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      GF_RENDERING_SERVER_URL: http://renderer:8081/render
#      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
#      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - loki
      - renderer
    networks:
      - loki

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    ports:
      - "8081:8081"
    environment:
      - ENABLE_METRICS=true
    networks:
      - loki